# Alertmanager configuration for DevHub
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'devhub-alerts@yourdomain.com'
  smtp_auth_username: 'alerts@yourdomain.com'
  smtp_auth_password: 'your-email-password'

# Routing rules
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

# Alert receivers
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/webhook'
    send_resolved: true

- name: 'critical-alerts'
  email_configs:
  - to: 'devops-team@yourdomain.com'
    subject: '🚨 CRITICAL: DevHub Alert - {{ .GroupLabels.alertname }}'
    body: |
      Alert: {{ .GroupLabels.alertname }}
      Summary: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
      Description: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}

      Details:
      {{ range .Alerts }}
      - Instance: {{ .Labels.instance }}
      - Severity: {{ .Labels.severity }}
      - Started: {{ .StartsAt }}
      {{ end }}

      Dashboard: http://localhost:3001/d/devhub-overview
  slack_configs:
  - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    channel: '#devhub-alerts'
    title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      *Summary:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Instance:* {{ .Labels.instance }}
      *Severity:* {{ .Labels.severity }}
      {{ end }}

- name: 'warning-alerts'
  email_configs:
  - to: 'dev-team@yourdomain.com'
    subject: '⚠️ WARNING: DevHub Alert - {{ .GroupLabels.alertname }}'
    body: |
      Alert: {{ .GroupLabels.alertname }}
      Summary: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
      Description: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}

      This is a warning-level alert that may require attention.

      Dashboard: http://localhost:3001/d/devhub-overview

# Inhibition rules (suppress alerts based on other alerts)
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']